### ISSUE TITLE
use of tidyhydat rather than downloading HYDAT?

### ISSUE THREAD

**Issue by rchlumsk** [maseology/sHydrology#1]
Any thought to make tidyhydat a dependency and remove the need to manually download the database? Might make the use of the application a little bit easier as the database can be managed and updated directly in R without modifying the code first before launching. If there is a good reason to avoid that route I would be curious about that as well.

Cheers!

**Comment by maseology** [comment]
Thanks Rob, Frankly I had no idea of tidyhydat. Looks like a solution. I'd be curious: how quickly does the package update once WSC releases their quarterly databases?  Any idea?

**Comment by rchlumsk** [comment]
The `download_hydat` function grabs the latest WSC HYDAT database, so it can be updated manually whenever a new version is available from WSC. There would be a small gap in historical data as tidyhydat gets 30day realtime data but doesn't allow you to get historical data that is not in the HYDAT database (i.e. data available from the WSC pages between HYDAT releases), but other than that it might help make things a bit easier to manage for users. Anyway something to consider!
